name: MUNGE charm tests
on:
  workflow_call:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit

# TODO: Uncomment once some integration tests have been written for the MUNGE operator.
#  integration-test-munge-ready:
#    name: Integration tests for the munge-ready integration
#    needs:
#      - lint
#      - unit-test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Set up operator environment
#        uses: charmed-kubernetes/actions-operator@main
#        with:
#          provider: lxd
#      - name: Run integration tests for munge-ready
#        run: tox -e integration-munge-ready

# TODO: Uncomment once some integration tests have been written for the MUNGE operator.
#  integration-test-auth-munge:
#    name: Integration tests for the auth-munge integration
#    needs:
#      - lint
#      - unit-test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Set up operator environment
#        uses: charmed-kubernetes/actions-operator@main
#        with:
#          provider: lxd
#      - name: Run integration tests for auth-munge
#        run: tox -e integration-auth-munge
